import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./_components/Header/Header";
import "./globals.css";
import Footer from "./_components/Footer/Footer";
import AdSense from "./_components/Adsense/AdSense";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BRIEFLY - Your Source for Today's Top Headlines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { [key: string]: string }; // Adjust type based on your dynamic route
}>) {
  const pubId = process.env.GOOGLE_PUB_ID;

  return (
    <html lang="en">
      <head>
        <AdSense pId={pubId} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
